name: audiopath_mvp
description: MVP for hearing & speech development app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  audioplayers: ^5.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/content/